"""Add naming convention

Revision ID: 910affcdd6e8
Revises: cf1befaa1537
Create Date: 2024-05-09 10:55:28.866819

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '910affcdd6e8'
down_revision = 'cf1befaa1537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_charityproject_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_charityproject_name'), type_='unique')

    # ### end Alembic commands ###
